# This rule is not used by the project eck-custom-resources itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to es.eck.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: es.eck-resourcetemplatedata-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - resourcetemplatedata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - resourcetemplatedata/status
  verbs:
  - get
