# This rule is not used by the project eck-custom-resources itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over es.eck.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: es.eck-resourcetemplatedata-admin-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - resourcetemplatedata
  verbs:
  - '*'
- apiGroups:
  - es.eck.github.com
  resources:
  - resourcetemplatedata/status
  verbs:
  - get
