---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - componenttemplates
  - elasticsearchapikeys
  - elasticsearchroles
  - elasticsearchusers
  - indexlifecyclepolicies
  - indextemplates
  - indices
  - ingestpipelines
  - resourcetemplatedata
  - snapshotlifecyclepolicies
  - snapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - componenttemplates/finalizers
  - elasticsearchapikeys/finalizers
  - elasticsearchroles/finalizers
  - elasticsearchusers/finalizers
  - indexlifecyclepolicies/finalizers
  - indextemplates/finalizers
  - indices/finalizers
  - ingestpipelines/finalizers
  - resourcetemplatedata/finalizers
  - snapshotlifecyclepolicies/finalizers
  - snapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - componenttemplates/status
  - elasticsearchapikeys/status
  - elasticsearchroles/status
  - elasticsearchusers/status
  - indexlifecyclepolicies/status
  - indextemplates/status
  - indices/status
  - ingestpipelines/status
  - resourcetemplatedata/status
  - snapshotlifecyclepolicies/status
  - snapshotrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards
  - dataviews
  - indexpatterns
  - lens
  - savedsearches
  - spaces
  - visualizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards/finalizers
  - dataviews/finalizers
  - indexpatterns/finalizers
  - lens/finalizers
  - savedsearches/finalizers
  - spaces/finalizers
  - visualizations/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards/status
  - dataviews/status
  - indexpatterns/status
  - lens/status
  - savedsearches/status
  - spaces/status
  - visualizations/status
  verbs:
  - get
  - patch
  - update
