---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: projectconfigs.config.github.com
spec:
  group: config.github.com
  names:
    kind: ProjectConfig
    listKind: ProjectConfigList
    plural: projectconfigs
    singular: projectconfig
  scope: Namespaced
  versions:
  - name: v2
    schema:
      openAPIV3Schema:
        description: ProjectConfig is the Schema for the projectconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of ProjectConfig
            properties:
              elasticsearch:
                description: foo is an example field of ProjectConfig. Edit projectconfig_types.go
                  to remove/update
                properties:
                  authentication:
                    description: ElasticsearchAuthentication Definition of Elasticsearch
                      authentication
                    properties:
                      apiKey:
                        description: APIKey Definition of APIKey authentication
                        properties:
                          apiKey:
                            minLength: 0
                            type: string
                        required:
                        - apiKey
                        type: object
                      usernamePasswordSecret:
                        description: UsernamePasswordAuthentication Definition of
                          Username/Password authentication
                        properties:
                          secretName:
                            minLength: 0
                            type: string
                          userName:
                            minLength: 0
                            type: string
                        required:
                        - secretName
                        - userName
                        type: object
                    type: object
                  certificate:
                    description: PublicCertificate Configuration for public certificate
                      used for communication with target
                    properties:
                      certificateKey:
                        minLength: 0
                        type: string
                      secretName:
                        minLength: 0
                        type: string
                    required:
                    - certificateKey
                    - secretName
                    type: object
                  enabled:
                    type: boolean
                  url:
                    minLength: 0
                    type: string
                required:
                - enabled
                - url
                type: object
              kibana:
                description: KibanaSpec Definition of target elasticsearch cluster
                properties:
                  authentication:
                    description: KibanaAuthentication Definition of Kibana authentication
                    properties:
                      apiKeySecret:
                        description: APIKey Definition of APIKey authentication
                        properties:
                          apiKey:
                            minLength: 0
                            type: string
                        required:
                        - apiKey
                        type: object
                      usernamePasswordSecret:
                        description: UsernamePasswordAuthentication Definition of
                          Username/Password authentication
                        properties:
                          secretName:
                            minLength: 0
                            type: string
                          userName:
                            minLength: 0
                            type: string
                        required:
                        - secretName
                        - userName
                        type: object
                    type: object
                  certificate:
                    description: PublicCertificate Configuration for public certificate
                      used for communication with target
                    properties:
                      certificateKey:
                        minLength: 0
                        type: string
                      secretName:
                        minLength: 0
                        type: string
                    required:
                    - certificateKey
                    - secretName
                    type: object
                  enabled:
                    type: boolean
                  url:
                    minLength: 0
                    type: string
                required:
                - enabled
                - url
                type: object
            type: object
          status:
            description: status defines the observed state of ProjectConfig
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
