apiVersion: es.eck.github.com/v1alpha1
kind: ResourceTemplateData
metadata:
  labels:
    app.kubernetes.io/name: eck-custom-resources
    app.kubernetes.io/managed-by: kustomize
  name: resourcetemplatedata-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  values:
    routing:
      destination: my-index
      conditions:
        byNamespace: >- 
            ctx?._source?.metadata?.namespace == "default"
        byKind: >-
          ctx?._source?.kind == "Elasticsearch"